version: '3.8'

services:
  db:
    image: postgres:16
    container_name: budgetbot-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budgetbot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    external: true
    name: c258ad4d2fa2438d3119648e6d0428693d835a2e6ade584507b6187dd92cfb98
